#pragma once

#include "block/Block.h"
#include "block/BlockDestructionProgress.h"
#include "block/BlockPos.h"

#include "blockentity/BlockEntity.h"
#include "blockentity/ChestBlockEntity.h"
#include "blockentity/SignBlockEntity.h"
#include "blockentity/TheEndGatewayEntity.h"

#include "client/app/CGameNetworkManager.h"
#include "client/app/CInput.h"
#include "client/app/CMinecraftApp.h"
#include "client/app/CPlatformNetworkManagerNintendo.h"
#include "client/app/CProfile.h"
#include "client/app/ConsoleUIController.h"
#include "client/app/Input.h"
#include "client/app/Options.h"
#include "client/app/System.h"

#include "client/file/File.h"
#include "client/file/FileInputStream.h"
#include "client/file/FileOutputStream.h"

#include "client/resource/texture/TextureAtlas.h"
#include "client/resource/texture/Textures.h"

#include "client/resource/ArrayWithLength.h"
#include "client/resource/NonNullList.h"
#include "client/resource/ResourceLocation.h"
#include "client/resource/pair.h"
#include "client/resource/shared_ptr.h"
#include "client/resource/unordered_map.h"
#include "client/resource/vector.h"
#include "client/resource/wstring.h"

#include "client/C4JThreadImpl.h"
#include "client/Minecraft.h"

#include "container/AbstractContainerMenu.h"
#include "container/Container.h"
#include "container/Inventory.h"
#include "container/SimpleContainer.h"

#include "entity/effect/MobEffect.h"
#include "entity/effect/MobEffectInstance.h"

#include "entity/player/Abilities.h"
#include "entity/player/FoodData.h"
#include "entity/player/LocalPlayer.h"
#include "entity/player/Player.h"
#include "entity/player/PlayerUID.h"
#include "entity/player/RemotePlayer.h"
#include "entity/player/ServerPlayer.h"

#include "entity/AgableMob.h"
#include "entity/Animal.h"
#include "entity/AreaEffectCloud.h"
#include "entity/ArmorStand.h"
#include "entity/DamageSource.h"
#include "entity/Entity.h"
#include "entity/EntityTickCache.h"
#include "entity/EvocationFangs.h"
#include "entity/ItemEntity.h"
#include "entity/ItemFrame.h"
#include "entity/LivingEntity.h"
#include "entity/Minecart.h"
#include "entity/Mob.h"
#include "entity/Monster.h"
#include "entity/Painting.h"
#include "entity/PathfinderMob.h"
#include "entity/PrimedTnt.h"
#include "entity/Sheep.h"
#include "entity/Slime.h"
#include "entity/SpectralArrow.h"
#include "entity/TippableArrow.h"
#include "entity/Zombie.h"

#include "item/BlockItem.h"
#include "item/BowItem.h"
#include "item/EmptyMapItem.h"
#include "item/Item.h"
#include "item/ItemInstance.h"

#include "nbt/ByteArrayTag.h"
#include "nbt/ByteTag.h"
#include "nbt/CompoundTag.h"
#include "nbt/DoubleTag.h"
#include "nbt/FloatTag.h"
#include "nbt/IntTag.h"
#include "nbt/ListTag.h"
#include "nbt/LongTag.h"
#include "nbt/ShortTag.h"
#include "nbt/StringTag.h"
#include "nbt/Tag.h"

#include "network/NQRNetworkManager.h"
#include "network/NQRNetworkManager_WiiU.h"
#include "network/NQRNetworkPlayer.h"
#include "network/NintendoVoiceChat_WiiU.h"

#include "network/listener/ClientPacketListener.h"
#include "network/listener/ServerConnectionListener.h"
#include "network/listener/ServerGamePacketListenerImpl.h"

#include "network/packet/clientbound/ClientbooundSetEntityMotionPacket.h"
#include "network/packet/clientbound/ClientboundAddPlayerPacket.h"
#include "network/packet/clientbound/ClientboundBlockEventPacket.h"
#include "network/packet/clientbound/ClientboundBlockUpdatePacket.h"
#include "network/packet/clientbound/ClientboundChatPacket.h"
#include "network/packet/clientbound/ClientboundContainerClosePacket.h"
#include "network/packet/clientbound/ClientboundLoginPacket.h"
#include "network/packet/clientbound/ClientboundMapItemDataPacket.h"
#include "network/packet/clientbound/ClientboundPreLoginPacket.h"
#include "network/packet/clientbound/ClientboundSoundPacket.h"

#include "network/packet/serverbound/ServerboundContainerClickPacket.h"
#include "network/packet/serverbound/ServerboundInteractPacket.h"
#include "network/packet/serverbound/ServerboundMovePlayerPacket.h"
#include "network/packet/serverbound/ServerboundPlayerActionPacket.h"
#include "network/packet/serverbound/ServerboundPreLoginPacket.h"
#include "network/packet/serverbound/ServerboundSetCarriedItemPacket.h"
#include "network/packet/serverbound/ServerboundSetCreativeModeSlotPacket.h"
#include "network/packet/serverbound/ServerboundSignUpdatePacket.h"
#include "network/packet/serverbound/ServerboundUseItemOnPacket.h"
#include "network/packet/serverbound/ServerboundUseItemPacket.h"

#include "network/packet/CraftItemPacket.h"
#include "network/packet/DisconnectPacket.h"
#include "network/packet/Packet.h"

#include "network/server/MinecraftServer.h"
#include "network/server/PlayerList.h"

#include "rendering/buffer/BufferBuilder.h"
#include "rendering/buffer/BufferedImage.h"

#include "rendering/CameraController.h"
#include "rendering/Font.h"
#include "rendering/GlStateManager.h"
#include "rendering/Tesselator.h"

#include "ui/control/UIControl.h"
#include "ui/control/UIControl_Base.h"
#include "ui/control/UIControl_List.h"
#include "ui/control/UIControl_MultiList.h"

#include "ui/fui/fuiFile.h"

#include "ui/logic/MultiListSliderLogic.h"

#include "ui/scene/UIScene.h"

#include "ui/Gui.h"
#include "ui/UIString.h"

#include "utils/AABB.h"
#include "utils/CMath.h"
#include "utils/ClickType.h"
#include "utils/Color.h"
#include "utils/Common.h"
#include "utils/Direction.h"
#include "utils/EUIScene.h"
#include "utils/EquipmentSlot.h"
#include "utils/GameType.h"
#include "utils/HitResult.h"
#include "utils/InteractionHand.h"
#include "utils/MenuBuilder.h"
#include "utils/NBTUtils.h"
#include "utils/ParticleType.h"
#include "utils/SoundEvent.h"
#include "utils/SoundSource.h"
#include "utils/TelemetryManager.h"
#include "utils/VTable.h"
#include "utils/VTable_Entity.h"
#include "utils/VTable_Item.h"
#include "utils/VTable_Tag.h"
#include "utils/VTable_TelemetryManager.h"
#include "utils/Vec3.h"
#include "utils/ePARTICLE_TYPE.h"
#include "utils/stb_image.h"

#include "world/gamemode/ServerPlayerGameMode.h"

#include "world/map/MapDecoration.h"
#include "world/map/MapItemSavedData.h"
#include "world/map/MapPalette.h"
#include "world/map/SavedData.h"

#include "world/Level.h"
#include "world/ServerLevel.h"
